web/foodtasker/urls.py
from django.conf.urls import url, include
from django.urls import include, path

from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.conf import settings

from foodtaskerapp import views, apis

urlpatterns = [
    path('site/admin/', admin.site.urls),
    path('', views.home, name='home'),

    # Restaurant
    path('restaurant/sign-in/', auth_views.LoginView.as_view(template_name='restaurant/sign_in.html'), name='restaurant-sign-in'),

    path('restaurant/sign-out/', auth_views.LogoutView.as_view(), name='restaurant-sign-out'),
    url(r'^restaurant/sign-up', views.restaurant_sign_up,
        name = 'restaurant-sign-up'),
    url(r'^restaurant/$', views.restaurant_home, name = 'restaurant-home'),

    url(r'^restaurant/account/$', views.restaurant_account, name = 'restaurant-account'),
    url(r'^restaurant/meal/$', views.restaurant_meal, name = 'restaurant-meal'),
    url(r'^restaurant/meal/add/$', views.restaurant_add_meal, name = 'restaurant-add-meal'),
    url(r'^restaurant/meal/edit/(?P<meal_id>\d+)/$', views.restaurant_edit_meal, name = 'restaurant-edit-meal'),
    url(r'^restaurant/order/$', views.restaurant_order, name = 'restaurant-order'),
    url(r'^restaurant/report/$', views.restaurant_report, name = 'restaurant-report'),

    # Sign In/ Sign Up/ Sign Out
    path('api/social/', include('rest_framework_social_oauth2.urls')),
    # /convert-token (sign in/ sign up)
    # /revoke-token (sign out)
    url(r'^api/restaurant/order/notification/(?P<last_request_time>.+)/$', apis.restaurant_order_notification),


    # APIs for CUSTOMERS
    url(r'^api/customer/restaurants/$', apis.customer_get_restaurants),
    url(r'^api/customer/meals/(?P<restaurant_id>\d+)/$', apis.customer_get_meals),
    url(r'^api/customer/order/add/$', apis.customer_add_order),
    url(r'^api/customer/order/latest/$', apis.customer_get_latest_order),
    url(r'^api/customer/driver/location/$', apis.customer_driver_location),


    # APIs for DRIVERS
    url(r'^api/driver/orders/ready/$', apis.driver_get_ready_orders),
    url(r'^api/driver/order/pick/$', apis.driver_pick_order),
    url(r'^api/driver/order/latest/$', apis.driver_get_latest_order),
    url(r'^api/driver/order/complete/$', apis.driver_complete_order),
    url(r'^api/driver/revenue/$', apis.driver_get_revenue),
    url(r'^api/driver/location/update/$', apis.driver_update_location),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

web/foodtaskerapp/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone

# Create your models here.
class Restaurant(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='restaurant')
    name = models.CharField(max_length=500)
    phone = models.CharField(max_length=500)
    address = models.CharField(max_length=500)
    logo = models.ImageField(upload_to='restaurant_logo/', blank=False)

    def __str__(self):
        return self.name

class Customer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='customer')
    avatar = models.CharField(max_length=500)
    phone = models.CharField(max_length=500, blank=True)
    address = models.CharField(max_length=500, blank=True)

    def __str__(self):
        return self.user.get_full_name()

class Driver(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='driver')
    avatar = models.CharField(max_length=500)
    phone = models.CharField(max_length=500, blank=True)
    address = models.CharField(max_length=500, blank=True)
    location = models.CharField(max_length=500, blank=True)

    def __str__(self):
        return self.user.get_full_name()

class Meal(models.Model):
    restaurant = models.ForeignKey(Restaurant,on_delete=models.CASCADE,)
    name = models.CharField(max_length=500)
    short_description = models.CharField(max_length=500)
    image = models.ImageField(upload_to='meal_images/', blank=False)
    price = models.IntegerField(default=0)

    def __str__(self):
        return self.name

class Order(models.Model):
    COOKING = 1
    READY = 2
    ONTHEWAY = 3
    DELIVERED = 4

    STATUS_CHOICES = (
        (COOKING, "Cooking"),
        (READY, "Ready"),
        (ONTHEWAY, "On the way"),
        (DELIVERED, "Delivered"),
    )

    customer = models.ForeignKey(Customer,on_delete=models.CASCADE,)
    restaurant = models.ForeignKey(Restaurant,on_delete=models.CASCADE,)
    driver = models.ForeignKey(Driver, on_delete=models.CASCADE,blank = True, null = True)
    address = models.CharField(max_length=500)
    total = models.IntegerField()
    status = models.IntegerField(choices = STATUS_CHOICES)
    created_at = models.DateTimeField(default = timezone.now)
    picked_at = models.DateTimeField(blank = True, null = True)

    def __str__(self):
        return str(self.id)


class OrderDetails(models.Model):
    order = models.ForeignKey(Order,on_delete=models.CASCADE, related_name='order_details')
    meal = models.ForeignKey(Meal,on_delete=models.CASCADE)
    quantity = models.IntegerField()
    sub_total = models.IntegerField()

    def __str__(self):
        return str(self.id)

web/foodtaskerapp/forms.py
from django import forms

from django.contrib.auth.models import User
from foodtaskerapp.models import Restaurant, Meal

class UserForm(forms.ModelForm):
    email = forms.CharField(max_length=100, required=True)
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ("username", "password", "first_name", "last_name", "email")

class UserFormForEdit(forms.ModelForm):
    email = forms.CharField(max_length=100, required=True)

    class Meta:
        model = User
        fields = ("first_name", "last_name", "email")

class RestaurantForm(forms.ModelForm):
    class Meta:
        model = Restaurant
        fields = ("name", "phone", "address", "logo")

class MealForm(forms.ModelForm):
    class Meta:
        model = Meal
        exclude = ("restaurant",)

web/foodtaskerapp/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required

from foodtaskerapp.forms import UserForm, RestaurantForm, UserFormForEdit, MealForm
from django.contrib.auth import authenticate, login

from django.contrib.auth.models import User
from foodtaskerapp.models import Meal, Order, Driver

from django.db.models import Sum, Count, Case, When

# Create your views here.
def home(request):
    return redirect(restaurant_home)

@login_required(login_url='/restaurant/sign-in/')
def restaurant_home(request):
    return redirect(restaurant_order)

@login_required(login_url='/restaurant/sign-in/')
def restaurant_account(request):
    user_form = UserFormForEdit(instance = request.user)
    restaurant_form = RestaurantForm(instance = request.user.restaurant)

    if request.method == "POST":
        user_form = UserFormForEdit(request.POST, instance = request.user)
        restaurant_form = RestaurantForm(request.POST, request.FILES, instance = request.user.restaurant)

        if user_form.is_valid() and restaurant_form.is_valid():
            user_form.save()
            restaurant_form.save()

    return render(request, 'restaurant/account.html', {
        "user_form": user_form,
        "restaurant_form": restaurant_form
    })

@login_required(login_url='/restaurant/sign-in/')
def restaurant_meal(request):
    meals = Meal.objects.filter(restaurant = request.user.restaurant).order_by("-id")
    return render(request, 'restaurant/meal.html', {"meals": meals})

@login_required(login_url='/restaurant/sign-in/')
def restaurant_add_meal(request):
    form = MealForm()

    if request.method == "POST":
        form = MealForm(request.POST, request.FILES)

        if form.is_valid():
            meal = form.save(commit=False)
            meal.restaurant = request.user.restaurant
            meal.save()
            return redirect(restaurant_meal)

    return render(request, 'restaurant/add_meal.html', {
        "form": form
    })

@login_required(login_url='/restaurant/sign-in/')
def restaurant_edit_meal(request, meal_id):
    form = MealForm(instance = Meal.objects.get(id = meal_id))

    if request.method == "POST":
        form = MealForm(request.POST, request.FILES, instance = Meal.objects.get(id = meal_id))

        if form.is_valid():
            form.save()
            return redirect(restaurant_meal)

    return render(request, 'restaurant/edit_meal.html', {
        "form": form
    })


@login_required(login_url='/restaurant/sign-in/')
def restaurant_order(request):
    if request.method == "POST":
        order = Order.objects.get(id = request.POST["id"], restaurant = request.user.restaurant)

        if order.status == Order.COOKING:
            order.status = Order.READY
            order.save()

    orders = Order.objects.filter(restaurant = request.user.restaurant).order_by("-id")
    return render(request, 'restaurant/order.html', {"orders": orders})

@login_required(login_url='/restaurant/sign-in/')
def restaurant_report(request):
    # Calculate revenue and number of order by current week
    from datetime import datetime, timedelta

    revenue = []
    orders = []

    # Calculate weekdays
    today = datetime.now()
    current_weekdays = [today + timedelta(days = i) for i in range(0 - today.weekday(), 7 - today.weekday())]

    for day in current_weekdays:
        delivered_orders = Order.objects.filter(
            restaurant = request.user.restaurant,
            status = Order.DELIVERED,
            created_at__year = day.year,
            created_at__month = day.month,
            created_at__day = day.day
        )
        revenue.append(sum(order.total for order in delivered_orders))
        orders.append(delivered_orders.count())


    # Top 3 Meals
    top3_meals = Meal.objects.filter(restaurant = request.user.restaurant)\
                     .annotate(total_order = Sum('orderdetails__quantity'))\
                     .order_by("-total_order")[:3]

    meal = {
        "labels": [meal.name for meal in top3_meals],
        "data": [meal.total_order or 0 for meal in top3_meals]
    }

    # Top 3 Drivers
    top3_drivers = Driver.objects.annotate(
        total_order = Count(
            Case (
                When(order__restaurant = request.user.restaurant, then = 1)
            )
        )
    ).order_by("-total_order")[:3]

    driver = {
        "labels": [driver.user.get_full_name() for driver in top3_drivers],
        "data": [driver.total_order for driver in top3_drivers]
    }

    return render(request, 'restaurant/report.html', {
        "revenue": revenue,
        "orders": orders,
        "meal": meal,
        "driver": driver
    })

def restaurant_sign_up(request):
    user_form = UserForm()
    restaurant_form = RestaurantForm()

    if request.method == "POST":
        user_form = UserForm(request.POST)
        restaurant_form = RestaurantForm(request.POST, request.FILES)

        if user_form.is_valid() and restaurant_form.is_valid():
            new_user = User.objects.create_user(**user_form.cleaned_data)
            new_restaurant = restaurant_form.save(commit=False)
            new_restaurant.user = new_user
            new_restaurant.save()

            login(request, authenticate(
                username = user_form.cleaned_data["username"],
                password = user_form.cleaned_data["password"]
            ))

            return redirect(restaurant_home)

    return render(request, "restaurant/sign_up.html", {
        "user_form": user_form,
        "restaurant_form": restaurant_form
    })

web/foodtaskerapp/templates/restaurant/account.html
{% extends 'restaurant/base.html' %}
{% load bootstrap4 %}

{% block page %}
    <div class="offset-lg-2 col-lg-8">
        <div class="panel">
            <div class="panel-heading bg-blue">
                <h4 class="panel-title text-center text-white">
                    Account
                </h4>
            </div>
            <div class="panel-body">
                <form method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    {% bootstrap_form user_form %}
                    {% bootstrap_form restaurant_form %}
                    <button type="submit" class="btn btn-pink">Update</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

web/foodtaskerapp/templates/restaurant/add_meal.html
{% extends 'restaurant/base.html' %}
{% load bootstrap4 %}

{% block page %}
    <div class="offset-lg-2 col-lg-8">
        <div class="panel">
            <div class="panel-heading bg-blue">
                <h4 class="panel-title text-center text-white">
                    Add Meal
                </h4>
            </div>
            <div class="panel-body">
                <form method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    {% bootstrap_form form %}
                    <button type="submit" class="btn btn-pink">Create</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

web/foodtaskerapp/templates/restaurant/base.html
{% extends 'base.html' %}

{% block title %} Restaurant {% endblock %}

{% block script %}
    <script>
        $(document).ready(function() {
            var now = new Date();
            setInterval(function() {
                $.ajax({
                    url: '/api/restaurant/order/notification/' + now.toISOString() + '/',
                    method: 'GET',
                    success: function(data) {
                        if (data['notification'] === 0) {
                            $('.badge').text('');
                        } else {
                            $('.badge').text(data['notification']);
                        }
                    }
                })
            }, 3000)
        })

    </script>
{% endblock %}

{% block sidebar %}

    {% url 'restaurant-order' as restaurant_order_url %}
    {% url 'restaurant-meal' as restaurant_meal_url %}
    {% url 'restaurant-report' as restaurant_report_url %}
    {% url 'restaurant-account' as restaurant_account_url %}

    <div class="text-center">
      <img class="img-circle" src="{{ MEDIA_URL }}{{ request.user.restaurant.logo }}"
          width="70" height="70" />
      <br/>
      <br/>
      <h4>Hi, {{ request.user.get_full_name }}</h4>
      <h5>{{ request.user.restaurant.name }}</h5>
    </div>

    <div class="list-group">
      <span class="text-uppercase">Dashboard</span>

      <a href="{% url 'restaurant-order' %}"
          class="list-group-item {% if request.path == restaurant_order_url %} active {% endif %} ">
          Orders
          <span class="badge"></span>
      </a>
      <a href="{% url 'restaurant-meal' %}"
          class="list-group-item {% if request.path == restaurant_meal_url %} active {% endif %} ">Meals</a>
      <a href="{% url 'restaurant-report' %}"
          class="list-group-item {% if request.path == restaurant_report_url %} active {% endif %} ">Reports</a>

      <span class="text-uppercase">Profile</span>
      <a href="{% url 'restaurant-account' %}"
          class="list-group-item {% if request.path == restaurant_account_url %} active {% endif %} ">Account</a>
    </div>

    <div class="text-center">
      <a href="{% url 'restaurant-sign-out' %}?next={{ request.path }}"
          class="btn btn-pink">Logout</a>
    </div>

{% endblock %}

web/foodtaskerapp/templates/restaurant/edit_meal.html
{% extends 'restaurant/base.html' %}
{% load bootstrap4 %}

{% block page %}
    <div class="offset-lg-2 col-lg-8">
        <div class="panel">
            <div class="panel-heading bg-blue">
                <h4 class="panel-title text-center text-white">
                    Edit Meal
                </h4>
            </div>
            <div class="panel-body">
                <form method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    {% bootstrap_form form %}
                    <button type="submit" class="btn btn-pink">Update</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

web/foodtaskerapp/templates/restaurant/meal.html
{% extends 'restaurant/base.html' %}

{% block page %}

    <div class="panel">
        <div class="panel-heading bg-blue">
            <h4 class="panel-title text-center text-white">Meals</h4>
        </div>
        <div class="panel-body">
            <div class="text-right">
                <a href="{% url 'restaurant-add-meal' %}" class="btn btn-pink">Add Meal</a>
                <br/>
                <br/>
            </div>

            <table class="table table-bordered table-hover table-striped">
                <thead>
                  <tr class="bg-gray text-white">
                    <th>Id</th>
                    <th>Name</th>
                    <th>Short Description</th>
                    <th>Price</th>
                    <th class="text-center">Image</th>
                  </tr>
                </thead>
                <tbody>
                    {% for meal in meals %}
                        <tr>
                          <td scope="row">{{ meal.id }}</td>
                          <td><a href="{% url 'restaurant-edit-meal' meal.id %}">{{ meal.name }}</a></td>
                          <td>{{ meal.short_description }}</td>
                          <td>{{ meal.price }}</td>
                          <td class="text-center"><img class="img-rounded"
                              src="{{ MEDIA_URL }}{{ meal.image }}" width="50" height="50"></td>
                        </tr>

                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>



{% endblock %}

web/foodtaskerapp/templates/restaurant/order.html
{% extends 'restaurant/base.html' %}

{% block page %}

    <div class="panel">
        <div class="panel-heading bg-blue">
            <h4 class="panel-title text-center text-white">Orders</h4>
        </div>
        <div class="panel-body">
            <br/>
            <table class="table table-bordered table-hover table-striped">
                <thead>
                  <tr class="bg-gray text-white">
                    <th>Id</th>
                    <th>Order Details</th>
                    <th>Customer</th>
                    <th>Driver</th>
                    <th>Total</th>
                    <th>Status</th>
                    <th>Action</th>
                  </tr>
                </thead>
                <tbody>
                    {% for order in orders %}
                        <tr>
                            <td scope="row">{{ order.id }}</td>
                            <td>
                              {% for od in order.order_details.all %}
                                  {{ od.meal.name }} {{ od.meal.price }}
                                  x {{ od.quantity }} = ${{ od.sub_total }}
                              {% endfor %}
                            </td>
                            <td>{{ order.customer }}</td>
                            <td>{{ order.driver }}</td>
                            <td>{{ order.total }}</td>
                            <td>{{ order.get_status_display }}</td>
                            <td>
                                {% if order.status == 1 %}
                                    <form method="POST">
                                      {% csrf_token %}
                                      <input name="id" value="{{ order.id }}" hidden>
                                      <button class="btn btn-success">Ready</button>
                                    </form>
                                {% endif %}
                            </td>
                        </tr>
                    {% endfor %}

                </tbody>
            </table>
        </div>
    </div>

{% endblock %}

web/foodtaskerapp/templates/restaurant/report.html
{% extends 'restaurant/base.html' %}

{% block script %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.2.2/Chart.min.js"></script>
{% endblock %}

{% block page %}

    <div class="row">
        <div class="col-lg-8">

            <!-- Revenue by Week -->
            <div class="panel">
                <div class="panel-heading bg-blue">
                  <h4 class="panel-title text-center text-white">
                      Revenue by Week
                  </h4>
                </div>
                <div class="panel-body">
                    <canvas id="revenueChart" height="110"></canvas>
                    <script>
                        var ctx = document.getElementById("revenueChart").getContext("2d");
                        var data = {
                            labels: ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"],
                            datasets: [
                                {
                                    label: "Revenue by Week",
                                    backgroundColor: "rgba(54,162,235,0.9)",
                                    hoverBackgroundColor: "rgba(54,162,235,1)",
                                    data: {{ revenue }}
                                }
                            ]
                        };

                        new Chart(ctx, {
                          type: 'bar',
                          data: data
                        });

                    </script>
                </div>
            </div>

            <!-- Orders by Week -->
            <div class="panel">
                <div class="panel-heading bg-blue">
                  <h4 class="panel-title text-center text-white">
                      Order by Week
                  </h4>
                </div>
                <div class="panel-body">
                    <canvas id="orderChart" height="110"></canvas>
                    <script>
                        var ctx = document.getElementById("orderChart").getContext("2d");
                        var data = {
                            labels: ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"],
                            datasets: [
                                {
                                    label: "Revenue by Week",
                                    backgroundColor: "rgba(255,99,132,0.9)",
                                    hoverBackgroundColor: "rgba(255,99,132,1)",
                                    data: {{ orders }}
                                }
                            ]
                        };

                        new Chart(ctx, {
                          type: 'bar',
                          data: data
                        });

                    </script>
                </div>
            </div>


        </div>
        <div class="col-lg-4">

          <!-- TOP 3 Meals -->
          <div class="panel">
              <div class="panel-heading bg-blue">
                <h4 class="panel-title text-center text-white">
                    Top 3 Meals
                </h4>
              </div>
              <div class="panel-body">
                  <canvas id="mealChart" height="242"></canvas>
                  <script>
                      var ctx = document.getElementById("mealChart").getContext("2d");
                      var data = {
                          labels: {{ meal.labels|safe }},
                          datasets: [
                              {
                                  backgroundColor: [
                                    "#36A2EB", "#FFCE56", "#FF6384"
                                  ],
                                  data: {{ meal.data }}
                              }
                          ]
                      };

                      new Chart(ctx, {
                        type: 'pie',
                        data: data
                      });

                  </script>
              </div>
          </div>

          <!-- TOP 3 Driver ALL TIME -->
          <div class="panel">
              <div class="panel-heading bg-blue">
                <h4 class="panel-title text-center text-white">
                    Top 3 Drivers
                </h4>
              </div>
              <div class="panel-body">
                  <canvas id="driverChart" height="242"></canvas>
                  <script>
                      var ctx = document.getElementById("driverChart").getContext("2d");
                      var data = {
                          labels: {{ driver.labels|safe }},
                          datasets: [
                              {
                                  backgroundColor: [
                                    "#36A2EB", "#FFCE56", "#FF6384"
                                  ],
                                  data: {{ driver.data }}
                              }
                          ]
                      };

                      new Chart(ctx, {
                        type: 'pie',
                        data: data
                      });

                  </script>
              </div>
          </div>
        </div>
    </div>

{% endblock %}

web/foodtaskerapp/templates/restaurant/sign_in.html
{% extends 'base_signup.html' %}
{% load bootstrap4 %}

{% block title %}Sign In{% endblock %}
{% block heading %}Restaurant - Sign In{% endblock %}

{% block content %}
    <form method="POST">
      {% csrf_token %}
      {% bootstrap_form form %}
      <button type="submit" class="btn btn-pink pull-right">Sign In</button>
    </form>
    <a href="{% url 'restaurant-sign-up' %}">Become a Restaurant</a>
{% endblock %}

web/foodtaskerapp/templates/restaurant/sign_up.html
{% extends 'base_signup.html' %}
{% load bootstrap4 %}

{% block title %}Sign In{% endblock %}
{% block heading %}Restaurant - Sign In{% endblock %}

{% block content %}
    <form method="POST" enctype="multipart/form-data">
      {% csrf_token %}
      {% bootstrap_form user_form %}
      {% bootstrap_form restaurant_form %}
      <button type="submit" class="btn btn-pink pull-right">Sign Up</button>
    </form>
    <a href="{% url 'restaurant-sign-in' %}">Already have an account?</a>
{% endblock %}